//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mltoolcli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TurkishStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TurkishStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mltoolcli.TurkishStrings", typeof(TurkishStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] bundle yaratılırken bir veya birden fazla hata meydana geldi..
        /// </summary>
        internal static string ErrMsg_BundleCreationFailed {
            get {
                return ResourceManager.GetString("ErrMsg_BundleCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: &apos;{0}&apos; geçerli bir komut değil.
        /// </summary>
        internal static string ErrMsg_DefaultStatement {
            get {
                return ResourceManager.GetString("ErrMsg_DefaultStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] dosya geçerli bir model veya veri seti dosyası değil..
        /// </summary>
        internal static string ErrMsg_FileNotValid {
            get {
                return ResourceManager.GetString("ErrMsg_FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] Dosya bulunamadı veya açılamıyor..
        /// </summary>
        internal static string ErrMsg_Load0 {
            get {
                return ResourceManager.GetString("ErrMsg_Load0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] Model ismi veya model içeriği bulunamadı..
        /// </summary>
        internal static string ErrMsg_ModelNotLoaded {
            get {
                return ResourceManager.GetString("ErrMsg_ModelNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] &apos;load&apos; komutunu kullanarak model ve veri seti yüklediniz mi?.
        /// </summary>
        internal static string ErrMsg_Train0 {
            get {
                return ResourceManager.GetString("ErrMsg_Train0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] platformunuz desteklenmiyor. Lütfen Windows veya Linux ile çalıştırın..
        /// </summary>
        internal static string ErrMsg_UnsupportedPlatform {
            get {
                return ResourceManager.GetString("ErrMsg_UnsupportedPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool: [HATA] &apos;{0}&apos; dosyasının türü tanınamadı. Model veya veri seti dosyası seçmelisiniz!.
        /// </summary>
        internal static string ErrMsg_ValidateFile0 {
            get {
                return ResourceManager.GetString("ErrMsg_ValidateFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çağırdığınız script dosyası bulunamadı!.
        /// </summary>
        internal static string ExcpMsg_ScriptNotFound {
            get {
                return ResourceManager.GetString("ExcpMsg_ScriptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   eval       Verilen değerin verilen model altındaki sonucunu bulur.
        /// </summary>
        internal static string HelpMsg_Eval {
            get {
                return ResourceManager.GetString("HelpMsg_Eval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   help       Bu mesajı gösterir.
        /// </summary>
        internal static string HelpMsg_Help {
            get {
                return ResourceManager.GetString("HelpMsg_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komutlar hakkında bilgi almak için &apos;mltool [komut] help&apos; kullanın..
        /// </summary>
        internal static string HelpMsg_Info {
            get {
                return ResourceManager.GetString("HelpMsg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komutlar:.
        /// </summary>
        internal static string HelpMsg_ListName {
            get {
                return ResourceManager.GetString("HelpMsg_ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   new        Yeni bir model veya veri seti dosyası oluşturur.
        /// </summary>
        internal static string HelpMsg_New {
            get {
                return ResourceManager.GetString("HelpMsg_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   train      Modeli, verilen veri seti dosyasını kullanarak eğitir.
        /// </summary>
        internal static string HelpMsg_Train {
            get {
                return ResourceManager.GetString("HelpMsg_Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanımı: mltool [komut] [argümanlar].
        /// </summary>
        internal static string HelpMsg_Usage {
            get {
                return ResourceManager.GetString("HelpMsg_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   eval help              Bu mesajı gösterir.
        /// </summary>
        internal static string Syntax_Eval0 {
            get {
                return ResourceManager.GetString("Syntax_Eval0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   eval [mdlPath] [num]   [num] sayısının [mdlPath] model dosyasındaki fonksiyon altında görüntüsünü hesaplar.
        /// </summary>
        internal static string Syntax_Eval1 {
            get {
                return ResourceManager.GetString("Syntax_Eval1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   new help             Bu mesajı gösterir.
        /// </summary>
        internal static string Syntax_New0 {
            get {
                return ResourceManager.GetString("Syntax_New0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   new model [name]     İsmi [name] olarak verilen modeli yaratır. Dosya program klasöründe oluşturulur.
        /// </summary>
        internal static string Syntax_New1 {
            get {
                return ResourceManager.GetString("Syntax_New1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   new dataset [name]   İsmi [name] olarak verilen ve rastgele veri içeren veri setini yaratır. Dosya program klasöründe oluşturulur.
        /// </summary>
        internal static string Syntax_New2 {
            get {
                return ResourceManager.GetString("Syntax_New2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new datase [name]    İsmi [name] olarak verilen model dosyası ve veri seti dosyasını yaratır. Dosyalar program klasöründe oluşturulur.
        /// </summary>
        internal static string Syntax_New3 {
            get {
                return ResourceManager.GetString("Syntax_New3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   train help                   Bu mesajı gösterir.
        /// </summary>
        internal static string Syntax_Train0 {
            get {
                return ResourceManager.GetString("Syntax_Train0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   train [dataPath] [mdlPath]   [dataPath] dataset dosyasını kullanarak [mdlPath] dosyasındaki modeli eğitir.
        /// </summary>
        internal static string Syntax_Train1 {
            get {
                return ResourceManager.GetString("Syntax_Train1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mltool v0101.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
