//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mltoolcli {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TurkishStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TurkishStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mltoolcli.TurkishStrings", typeof(TurkishStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HelpMsg_Help {
            get {
                return ResourceManager.GetString("HelpMsg_Help", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Exit {
            get {
                return ResourceManager.GetString("HelpMsg_Exit", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Train {
            get {
                return ResourceManager.GetString("HelpMsg_Train", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Test {
            get {
                return ResourceManager.GetString("HelpMsg_Test", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Load {
            get {
                return ResourceManager.GetString("HelpMsg_Load", resourceCulture);
            }
        }
        
        internal static string HelpMsg_New {
            get {
                return ResourceManager.GetString("HelpMsg_New", resourceCulture);
            }
        }
        
        internal static string ExcpMsg_ScriptNotFound {
            get {
                return ResourceManager.GetString("ExcpMsg_ScriptNotFound", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Usage {
            get {
                return ResourceManager.GetString("HelpMsg_Usage", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Info {
            get {
                return ResourceManager.GetString("HelpMsg_Info", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string HelpMsg_ListName {
            get {
                return ResourceManager.GetString("HelpMsg_ListName", resourceCulture);
            }
        }
    }
}
