//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mltoolcli {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TurkishStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TurkishStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mltoolcli.TurkishStrings", typeof(TurkishStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Help {
            get {
                return ResourceManager.GetString("HelpMsg_Help", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Train {
            get {
                return ResourceManager.GetString("HelpMsg_Train", resourceCulture);
            }
        }

        internal static string HelpMsg_Eval
        {
            get { return ResourceManager.GetString("HelpMsg_Eval", resourceCulture); }
        }

        internal static string HelpMsg_New {
            get {
                return ResourceManager.GetString("HelpMsg_New", resourceCulture);
            }
        }
        
        internal static string ExcpMsg_ScriptNotFound {
            get {
                return ResourceManager.GetString("ExcpMsg_ScriptNotFound", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Usage {
            get {
                return ResourceManager.GetString("HelpMsg_Usage", resourceCulture);
            }
        }
        
        internal static string HelpMsg_Info {
            get {
                return ResourceManager.GetString("HelpMsg_Info", resourceCulture);
            }
        }

        internal static string HelpMsg_ListName {
            get {
                return ResourceManager.GetString("HelpMsg_ListName", resourceCulture);
            }
        }
        
        internal static string Syntax_New0 {
            get {
                return ResourceManager.GetString("Syntax_New0", resourceCulture);
            }
        }
        
        internal static string Syntax_New1 {
            get {
                return ResourceManager.GetString("Syntax_New1", resourceCulture);
            }
        }
        
        internal static string Syntax_New2 {
            get {
                return ResourceManager.GetString("Syntax_New2", resourceCulture);
            }
        }
        
        internal static string Syntax_Train0 {
            get {
                return ResourceManager.GetString("Syntax_Train0", resourceCulture);
            }
        }
        
        internal static string Syntax_Train1 {
            get {
                return ResourceManager.GetString("Syntax_Train1", resourceCulture);
            }
        }
        
        internal static string Syntax_Eval0 {
            get {
                return ResourceManager.GetString("Syntax_Eval0", resourceCulture);
            }
        }
        
        internal static string Syntax_Eval1 {
            get {
                return ResourceManager.GetString("Syntax_Eval1", resourceCulture);
            }
        }
        
        internal static string ErrMsg_Train0 {
            get {
                return ResourceManager.GetString("ErrMsg_Train0", resourceCulture);
            }
        }

        internal static string ErrMsg_DefaultStatement {
            get {
                return ResourceManager.GetString("ErrMsg_DefaultStatement", resourceCulture);
            }
        }
        
        internal static string ErrMsg_Calculate0 {
            get {
                return ResourceManager.GetString("ErrMsg_Calculate0", resourceCulture);
            }
        }
        
        internal static string ErrMsg_ValidateFile0 {
            get {
                return ResourceManager.GetString("ErrMsg_ValidateFile0", resourceCulture);
            }
        }
    }
}
